config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from descriptions import views as des_views
from members import views as mem_views
from equipments import views as equ_views
from researches import views as res_views
from publications import views as pub_views
urlpatterns = [
    path('', include("core.urls", namespace="core")),
    path('people/', mem_views.member_page, name="people"),
    path('research/', res_views.research_page, name="research"),
    path('publication/', pub_views.publication_page, name="publication"),
    path('equitment/', equ_views.equitment_page, name="equitment"),


    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from descriptions import views as descriptions_views

app_name = "core"
urlpatterns = [
    path("", descriptions_views.home_page, name="home"),
]

descriptions/urls.py
from django.urls import path
from . import views


app_name = "descriptions"
urlpatterns = [
    path("/", views.home_page, name="home"),
]

core/models.py
from django.db import models

# Create your models here.


class TimeStampedMode(models.Model):
    """Time Stamped Model"""

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # 이 모델이 데이타베이스에 추가 되는 것을 원치 않아서 abstract = True 모델이긴 하지만 데이터베이스에 나타나지 않느 model을 의미함
    class Meta:
        abstract = True

descriptions/models.py
from django.db import models
from core import models as core_models

# Create your models here.


class AbstractItem(core_models.TimeStampedMode):
    """Abract Item"""

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class ParticipatingSociety(AbstractItem):
    """ParticipatingSociety Model Definition"""

    class Meta:
        verbose_name_plural = "Participating Societies"


class CooperativeResearchInstitution(AbstractItem):
    """CooperativeResearchInstitution Model Definition"""
    pass


class Description(core_models.TimeStampedMode):
    """Description Model Definition"""

    adress = models.CharField(max_length=80, default="")
    email = models.CharField(max_length=20, default="")
    contact_number = models.CharField(max_length=20, default="")
    description = models.TextField(default="")
    participating_societies = models.ManyToManyField(
        ParticipatingSociety, related_name="Description", blank=True)

    cooperative_research_institutions = models.ManyToManyField(
        CooperativeResearchInstitution, related_name="Description", blank=True)

equipments/models.py
from django.db import models

# reverse는 url name을 필요로 하는 funcion으로 url 을 return 함
from django.urls import reverse
from core import models as core_models

# Create your models here.


class Photo(core_models.TimeStampedMode):
    """Photo Model Definition"""

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="equiptment_photos")
    equiptment = models.ForeignKey(
        "Equiptment", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Equiptment(core_models.TimeStampedMode):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    def first_photo(self):
        try:
            photo = self.photos
        except ValueError:
            return None
        return photo.file.url

members/models.py
from django.db import models
from core import models as core_models

# Create your models here.


class Field(core_models.TimeStampedMode):
    """Photo Model Definition"""

    field = models.CharField(max_length=80, null=True, blank=True)
    description = models.TextField(default="", null=True, blank=True)
    member = models.ForeignKey(
        "Member", related_name="field", on_delete=models.CASCADE)


class Member(core_models.TimeStampedMode):
    """member Model Definition"""
    name = models.CharField(max_length=140)
    avatar = models.ImageField(upload_to="avatars", blank=True)
    description = models.TextField(default="", null=True, blank=True)

publications/models.py
from django.db import models

# reverse는 url name을 필요로 하는 funcion으로 url 을 return 함
from django.urls import reverse
from core import models as core_models

# Create your models here.


class Link(core_models.TimeStampedMode):
    """Photo Model Definition"""

   # caption = models.CharField(max_length=80, null=True, blank=True)
    description = models.TextField(default="", null=True, blank=True)
    url = models.URLField(("link"), max_length=200, blank=True, null=True)
    publication = models.ForeignKey(
        "Publication", related_name="link", on_delete=models.CASCADE)


class Publication(core_models.TimeStampedMode):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

researches/models.py
from django.db import models

# reverse는 url name을 필요로 하는 funcion으로 url 을 return 함
from django.urls import reverse
from core import models as core_models

# Create your models here.


class Photo(core_models.TimeStampedMode):
    """Photo Model Definition"""

    caption = models.CharField(max_length=80, null=True, blank=True)
    description = models.TextField(default="", null=True, blank=True)
    file = models.ImageField(upload_to="research_photos")
    research = models.ForeignKey(
        "Research", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Research(core_models.TimeStampedMode):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    def photos(self):
        return self.photos

    class Meta:
        verbose_name_plural = "Researches"

core/views.py
from django.shortcuts import render

# Create your views here.

descriptions/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
# Create your views here.


def home_page(request):
    CooperativeResearchInstitutions = models.CooperativeResearchInstitution.objects.all()
    return render(request, 'base.html', context={"CooperativeResearchInstitutions": CooperativeResearchInstitutions, })

equipments/views.py
from django.shortcuts import render
from django.http import HttpResponse

from . import models
# Create your views here.


def equitment_page(request):
    equiptments = models.Equiptment.objects.all()
    return render(request, "equitment.html", context={"equiptments": equiptments, })

members/views.py
from django.shortcuts import render
from django.http import HttpResponse

from . import models
# Create your views here.


def member_page(request):
    # return HttpResponse(content="hello")
    all_members = models.Member.objects.all()

    return render(request, "people.html", context={"members": all_members, })

publications/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
# Create your views here.


def publication_page(request):

    publications = models.Publication.objects.all()

    return render(request, 'publication.html', context={"publications": publications, })

researches/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
# Create your views here.


def research_page(request):

    researches = models.Research.objects.all()

    return render(request, "research.html", context={"researches": researches, })

templates/base.html
{%load static%}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{%static 'css/styles.css' %}">
    <script src="https://kit.fontawesome.com/0c928551ff.js" crossorigin="anonymous"></script>


    <title>Human Lab{% block page_title %}{% endblock page_title %}</title>

    <script>
        const toggleBtn = document.querySelector('.navbar-toggleBtn');
        const menu = document.querySelector('.navbar-menu');
        toggleBtn.addEventListener('click', () => {
            menu.classList.toggle('active');
        });
    </script>
    <style>
        body {
            margin: 0;
        }

        .navbar {
            display: flex;
            justify-content: space-between;
            align-items: center;
            background-color: blue;
            text-decoration: none;
            color: blanchedalmond;
            padding: 8px 12px;

        }

        a {
            color: white;
            text-decoration: none;
        }



        .navbar-logo {
            font-size: 24px;
        }


        .navbar-menu {
            display: flex;
            padding-left: 0;

        }

        .navbar-menu li {
            list-style: none;
            padding: 8px 12px;


        }

        .navbar-menu a {
            text-decoration: none;
        }

        .navbar-menu a:hover {
            color: white;
        }

        .navbar-menu li:hover {
            background-color: red;
            border-radius: 4px;

        }

        .navbar-toggleBtn {
            display: none;
            position: absolute;
            right: 32px;
            font-size: 24px;
        }

        @media screen and (max-width: 768px) {
            .navbar-menu.active {
                display: flex;

            }

            .navbar {
                flex-direction: column;
                align-items: flex-start;
                padding: 8px 24px;
            }

            .navbar-menu {
                display: none;
                flex-direction: column;
                align-items: center;
                width: 100%;
            }

            .navbar-menu li {
                width: 100%;
                text-align: center;
            }

            .navbar-toggleBtn {
                display: block;
            }



        }
    </style>
</head>

<body>


    <nav class=" navbar">
        <div class="navbar-logo">
            <a href="{%url 'core:home'%}">HUMAN LAB</a>
        </div>

        <ul class="navbar-menu">
            <li>
                <a href="{% url 'people'%}">People</a>
            </li>
            <li>
                <a href="{% url 'research'%}">Research</a>
            </li>
            <li>
                <a href="{% url 'publication'%}">Publication</a>
            </li>
            <li>
                <a href="{% url 'equitment'%}">Equitment</a>
            </li>
        </ul>
        <a href="#" class="navbar-toggleBtn">
            <i class="fas fa-bars"></i>
        </a>
        </div>
    </nav>
    {% block content %}
    <style>
        .info-header {
            height: 950px;
            text-align: center;
            line-height: 100vh;
            justify-content: center;
            background-repeat: no-repeat;
            background-color: #2196F3;
            background-position: center top;
            background-size: 100% auto;
        }

        .info-header .info {
            display: inline-block;
            line-height: normal;
            vertical-align: middle;
        }

        .info-header .info h1 {
            font-size: 36px;
            margin: 0;
            margin-bottom: 13px;
            color: white;
            font-weight: 400;
            width: 700px;
        }

        .info-header .info h2 {
            font-size: 16px;
            margin: 0;
            margin-bottom: 60px;
            color: white;
            font-weight: 400;
        }

        .info-header .info a {
            font-size: 14px;
            background-color: white;
            color: #464273;
            padding: 10px 40px;
            text-decoration: none;
            border-radius: 5px;
        }
    </style>
    <div class="info-header" style="background-image: url({% static 'background.png' %}); ">
        <div class=" info">
            <h1>인간-로봇 상호작용, 생체신호 기반 근전 의수, 스마트 재활 시스템 등을 개발</h1>
            <h2>두뇌의 제어 메커니즘을 규명하는 연구를 통해 인간 중심의 지능형 인터페이스를 개발</h2>
            <a href="{% url 'research'%}">더 알아보기</a>
        </div>
    </div>
    {% endblock  %}



</body>

</html>

templates/equitment.html
{% extends "base.html" %}

{% block page_title %}
| Equitment
{% endblock page_title %}

{% block content %}
<style>
        .center {
                text-align: center;
                margin-left: auto;
                margin-right: auto;

        }

        .name {
                grid-area: title;
        }

        .item-container {
                grid-area: item;
                display: grid;
                grid-template-areas:
                        'auto auto';
                grid-gap: 10px;

        }


        .grid-container {
                display: grid;
                grid-template-areas:
                        'title item item';
                grid-gap: 10px;
                padding: 10px;
                background-color: #f8f9fa;
                width: 1000px;



        }

        .grid-container>div {
                border-top: 3px solid #2196F3;
                border-width: thin;
                text-align: center;
                padding: 20px 0;
                font-size: 30px;
        }

        /*  .grid-container:nth-child(even) {
                background-color: rebeccapurple;
        } */
</style>

<div style="  border-radius:10px; ">
        <p class="center" style="font-weight: bold;  width:max-content;font-size: xx-large; ">
                Equitment</p>
        {% for equiptment in equiptments %}
        <div class="grid-container center">
                <div class="title " style="font-size: large; font-weight: bold;">{{equiptment.name}}</div>
                <div class="item-container">
                        {% for photo in equiptment.photos.all %}
                        <div class="item-box" style="margin: 10px;">
                                <img src="{{photo.file.url}}"
                                        style="height: 100px; width: auto;margin-bottom: 10px;"></img>
                                <p style="font-size: medium;">{{photo.caption}}</p>
                        </div>
                        {% endfor%}
                </div>
        </div>
        {% endfor%}








</div>

<!-- {% for equiptment in equiptments %}
<h1>{{equiptment.name}}<h1>

                {% endfor%}
                {% for photo in photos%}

                <span>{{photo.caption}}</span>
                <img src="{{photo.file.url}}" style="height: auto; width: auto;">

                {% endfor%} -->
{% endblock  %}

templates/people.html
{% extends "base.html" %}

{% block page_title %}
| People
{% endblock page_title %}

{% block content %}

<style>
    .center {
        text-align: center;
        margin-left: auto;
        margin-right: auto;

    }

    .photo {
        grid-area: photo;


    }

    .description {
        grid-area: description;
    }

    .grid-container {
        display: grid;
        grid-template-areas:
            'photo description description';
        /* grid-template-rows: auto 2fr; */
        grid-gap: 5px;
        padding: 10px;
        margin: 10px;
        overflow: visible;


    }

    .grid-container>div {
        border-top: 3px solid #2196F3;
        border-width: thin;

        padding: 20px 0;


    }

    .grid-container:nth-child(odd) {
        background-color: #f8f9fa;
    }




    .selector img {

        width: 100%;
        height: 100%;
    }
</style>

<div class="center" style="width:1000px">
    <div class="title " style="font-size: large; font-weight: bold;text-align: left;">교수님</div>
    {% for member in members %}
    <div class="grid-container ">
        <div class="selector" style="width:250px; height:300px">
            <img class="photo" src="{{member.avatar.url}}" alt="">
        </div>

        <div class=" description">
            <h1 style="text-align:left;font-size: x-large;">{{member.name}}</h1>
            <div style="text-align: center; font-size: medium;">{{member.description}}</div>
        </div>
    </div>
    {% endfor%}
</div>
</div>



{% endblock  %}

templates/publication.html
{% extends "base.html" %}

{% block page_title %}
| Publication
{% endblock page_title %}
{% block content %}
<style>
    .center {
        text-align: center;
        margin-left: auto;
        margin-right: auto;

    }
</style>


<!--  -->
<div class="center" style="/* background-color: #f8f9fa; */width: 1000px;">
    <p class="center"
        style="font-size:xx-large;font-weight:bold; margin-bottom: 2%;border-bottom: 3px solid #2196F3; width:max-content;">
        Publication</p>
    {% for publication in publications %}
    <h1 style="text-align: left; font-size: large; font-weight: bold;margin: 10px; padding: 10px;">
        {{publication.name}}</h1>
    {% for link in  publication.link.all%}
    <div style="text-align: left;">
        <ul>
            <li><a {%if link.url %} href=" {{link.url}}" {% endif %}>{{link.description}}</a></li>
        </ul>
    </div>

    {% endfor%}
    {% endfor%}
</div>
{% endblock  %}

templates/research.html
{% extends "base.html" %}

{% block page_title %}
| Research
{% endblock page_title %}

{% block content %}


<style>
    .center {
        text-align: center;
        margin-left: auto;
        margin-right: auto;

    }


    .photo {
        grid-area: photo;
    }

    .description {
        grid-area: description;
    }

    .grid-container {
        display: grid;
        grid-template-areas:
            'photo photo description description description';
        grid-template-rows: auto 1fr;
        grid-template-columns: auto 250px;

        grid-gap: 10px;
        /*      background-color: #2196F3; */
        padding: 10px;
        margin: 10px;
        overflow: visible;

    }

    .grid-container>div {
        /*  background-color: rgba(255, 255, 255, 0.8); */
        text-align: center;
        padding: 20px 0;

    }
</style>

<p class="center"
    style="font-size:xx-large;font-weight:bold; margin-bottom: 3%;/* border-bottom: 3px solid #2196F3; */ width:max-content; ">
    Research</p>

{% for research in researches %}
<div class="center" style="/* background-color :#f8f9fa;  border-bottom: solid 1px;*/">
    <div class="center" style="width: 1000px;">
        <div style="font-size: x-large;text-align: left;font-weight: bold;border-bottom: 3px solid #2196F3;">
            {{research.name}}</div>

        {% for photo in research.photos.all %}
        <div class="grid-container" style=" text-align: center;">

            <div class="photo" style=" margin-right: 10px; ">
                <img src="{{photo.file.url}}" style="height: auto; width: auto;margin-bottom: 3px;">
                <p> {{photo.caption}}</p>
            </div>
            <div class="description" style="text-align:  left; margin-top: 20px;  ">{{photo.description}}
            </div>
        </div>
        {% endfor %}

    </div>
</div>
{% endfor%}


{% endblock  %}